# Permalinks
permalink:           pretty

# Setup
title:               Josh Kendrick
tagline:             Setting Data
url:                 http://jnk83.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Josh Kendrick
  email:             jnkendr@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/jnk83

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
